--------------------------------------------------------
--  파일이 생성됨 - 화요일-10월-08-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence PRODUCT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "CATPOS"."PRODUCT_SEQ"  MINVALUE 1 MAXVALUE 10000 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CART
--------------------------------------------------------

  CREATE TABLE "CATPOS"."CART" 
   (	"ID" VARCHAR2(50 BYTE), 
	"PRODUCT_ID" VARCHAR2(100 BYTE), 
	"QUANTITY" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "CATPOS"."MEMBER" 
   (	"ID" VARCHAR2(50 BYTE), 
	"PASS" VARCHAR2(100 BYTE), 
	"PHONE" VARCHAR2(50 BYTE), 
	"HIRE_DATE" DATE DEFAULT SYSDATE, 
	"ROLE" VARCHAR2(20 BYTE) DEFAULT 'Staff', 
	"PRODUCT_ID" VARCHAR2(100 BYTE), 
	"NAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "CATPOS"."PRODUCT" 
   (	"PRODUCT_ID" VARCHAR2(100 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"PRICE" NUMBER DEFAULT 0, 
	"KIND" VARCHAR2(100 BYTE), 
	"STOCK" NUMBER DEFAULT 0, 
	"STATE" VARCHAR2(30 BYTE) DEFAULT 'Show'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SALES
--------------------------------------------------------

  CREATE TABLE "CATPOS"."SALES" 
   (	"ID" VARCHAR2(50 BYTE), 
	"PRODUCT_ID" VARCHAR2(100 BYTE), 
	"QUANTITY" NUMBER DEFAULT 0, 
	"TOTAL_PRICE" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into CATPOS.CART
SET DEFINE OFF;
REM INSERTING into CATPOS.MEMBER
SET DEFINE OFF;
Insert into CATPOS.MEMBER (ID,PASS,PHONE,HIRE_DATE,ROLE,PRODUCT_ID,NAME) values ('user02','2222','010-2222-2222',to_date('24/10/08','RR/MM/DD'),'Staff',null,'user02');
Insert into CATPOS.MEMBER (ID,PASS,PHONE,HIRE_DATE,ROLE,PRODUCT_ID,NAME) values ('user03','3333','010-3333-3333',to_date('24/10/08','RR/MM/DD'),'Staff',null,'user03');
Insert into CATPOS.MEMBER (ID,PASS,PHONE,HIRE_DATE,ROLE,PRODUCT_ID,NAME) values ('user04','4444','010-4444-4444',to_date('24/10/08','RR/MM/DD'),'Staff',null,'user04');
Insert into CATPOS.MEMBER (ID,PASS,PHONE,HIRE_DATE,ROLE,PRODUCT_ID,NAME) values ('ongsim','yedam','010-3076-3043',to_date('24/10/08','RR/MM/DD'),'Owner',null,'옹심');
Insert into CATPOS.MEMBER (ID,PASS,PHONE,HIRE_DATE,ROLE,PRODUCT_ID,NAME) values ('user01','1111','010-1111-1111',to_date('24/10/08','RR/MM/DD'),'Staff',null,'user01');
REM INSERTING into CATPOS.PRODUCT
SET DEFINE OFF;
Insert into CATPOS.PRODUCT (PRODUCT_ID,NAME,PRICE,KIND,STOCK,STATE) values ('1','로얄캐닌 캣 키튼',29900,'사료',50,'Show');
Insert into CATPOS.PRODUCT (PRODUCT_ID,NAME,PRICE,KIND,STOCK,STATE) values ('2','로얄캐닌 캣 인도어',39900,'사료',100,'Show');
Insert into CATPOS.PRODUCT (PRODUCT_ID,NAME,PRICE,KIND,STOCK,STATE) values ('3','내추럴발란스 캣',89900,'사료',30,'Hide');
Insert into CATPOS.PRODUCT (PRODUCT_ID,NAME,PRICE,KIND,STOCK,STATE) values ('4','츄르',3000,'간식',25,'Show');
Insert into CATPOS.PRODUCT (PRODUCT_ID,NAME,PRICE,KIND,STOCK,STATE) values ('5','동결건조',5000,'간식',40,'Show');
Insert into CATPOS.PRODUCT (PRODUCT_ID,NAME,PRICE,KIND,STOCK,STATE) values ('6','덴탈간식',2000,'간식',80,'Show');
Insert into CATPOS.PRODUCT (PRODUCT_ID,NAME,PRICE,KIND,STOCK,STATE) values ('7','강아지풀',5000,'장난감',150,'Show');
Insert into CATPOS.PRODUCT (PRODUCT_ID,NAME,PRICE,KIND,STOCK,STATE) values ('8','쥐',50000,'장난감',60,'Show');
Insert into CATPOS.PRODUCT (PRODUCT_ID,NAME,PRICE,KIND,STOCK,STATE) values ('9','낚시대',3000,'장난감',120,'Show');
Insert into CATPOS.PRODUCT (PRODUCT_ID,NAME,PRICE,KIND,STOCK,STATE) values ('10','레이저',1500,'장난감',45,'Show');
Insert into CATPOS.PRODUCT (PRODUCT_ID,NAME,PRICE,KIND,STOCK,STATE) values ('11','샴퓨',1500,'용품',45,'Show');
Insert into CATPOS.PRODUCT (PRODUCT_ID,NAME,PRICE,KIND,STOCK,STATE) values ('12','칫솔',500,'용품',45,'Hide');
Insert into CATPOS.PRODUCT (PRODUCT_ID,NAME,PRICE,KIND,STOCK,STATE) values ('13','숨숨집',30000,'용품',45,'Show');
Insert into CATPOS.PRODUCT (PRODUCT_ID,NAME,PRICE,KIND,STOCK,STATE) values ('14','캣타워',1000000,'용품',45,'Show');
REM INSERTING into CATPOS.SALES
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_CART
--------------------------------------------------------

  CREATE UNIQUE INDEX "CATPOS"."PK_CART" ON "CATPOS"."CART" ("ID", "PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_PRODUCT
--------------------------------------------------------

  CREATE UNIQUE INDEX "CATPOS"."PK_PRODUCT" ON "CATPOS"."PRODUCT" ("PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_SALES
--------------------------------------------------------

  CREATE UNIQUE INDEX "CATPOS"."PK_SALES" ON "CATPOS"."SALES" ("ID", "PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CART
--------------------------------------------------------

  ALTER TABLE "CATPOS"."CART" ADD CONSTRAINT "PK_CART" PRIMARY KEY ("ID", "PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CATPOS"."CART" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "CATPOS"."CART" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "CATPOS"."CART" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "CATPOS"."MEMBER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "CATPOS"."MEMBER" MODIFY ("ROLE" NOT NULL ENABLE);
  ALTER TABLE "CATPOS"."MEMBER" MODIFY ("HIRE_DATE" NOT NULL ENABLE);
  ALTER TABLE "CATPOS"."MEMBER" MODIFY ("PASS" NOT NULL ENABLE);
  ALTER TABLE "CATPOS"."MEMBER" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "CATPOS"."PRODUCT" ADD CONSTRAINT "PK_PRODUCT" PRIMARY KEY ("PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CATPOS"."PRODUCT" MODIFY ("STATE" NOT NULL ENABLE);
  ALTER TABLE "CATPOS"."PRODUCT" MODIFY ("STOCK" NOT NULL ENABLE);
  ALTER TABLE "CATPOS"."PRODUCT" MODIFY ("KIND" NOT NULL ENABLE);
  ALTER TABLE "CATPOS"."PRODUCT" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "CATPOS"."PRODUCT" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "CATPOS"."PRODUCT" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SALES
--------------------------------------------------------

  ALTER TABLE "CATPOS"."SALES" ADD CONSTRAINT "PK_SALES" PRIMARY KEY ("ID", "PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CATPOS"."SALES" MODIFY ("TOTAL_PRICE" NOT NULL ENABLE);
  ALTER TABLE "CATPOS"."SALES" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "CATPOS"."SALES" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "CATPOS"."SALES" MODIFY ("ID" NOT NULL ENABLE);
